---
title: "HML ID Assignment"
output:
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    css: custom.css
    social: menu
    logo: PAN_logo3.png
    favicon: PAN_logo3.png
runtime: shiny
editor_options:
  chunk_output_type: console
resource_files:
- www/deidentified_id_data.csv
---

```{=html}
<style type="text/css">

  .chart-title {  /* chart_title  */
    font-size: 22px;

</style>
```

```{r setup, include=FALSE}

library(tidyverse)
library(shiny)
library(flexdashboard)
# devtools::install_github(repo="haozhu233/kableExtra", ref="a6af5c0")
# Need to use the above to collapse rows properly
library(kableExtra)
# section to connect to Google Drive
library(googledrive)
# file with info for service account 
drive_auth(path = "pan-mindcrowd-uploads-ddf6b0dbe662.json")
# Option to silence the messages coming from the Google Drive library
options(googledrive_quiet = TRUE)

```

```{r load data}

# Downloads deidentified_id_data.csv and overwrites existing file
with_drive_quiet(
  drive_download(as_id("https://drive.google.com/file/d/1GbJUTmt96x50L9fDH4RGIIt05zoOWEbo"), overwrite = TRUE)
)
dat <- read.csv("deidentified_id_data.csv")

```

```{r server}

# Filter IDs by input area areaPick ------
id_choices <- reactive(
  filter(dat, area == input$areaPick)
)

# Filter data by selected ID idPick -------
picked_id_data <- reactive(
  filter(dat, part_id == input$idPick)
)

# Create new ID and add to dataset for confirmation -------
new_data <- reactive({
  req(input$newId)
  
  if(!is.na(dat$hml_id_undo[which(dat$part_id == (input$idPick))])){
    new_hml_id <- dat$hml_id_undo[which(dat$part_id == (input$idPick))]
  }else{
    new_hml_id <- paste0("HML", str_pad(sum(!is.na(dat$hml_id)) + sum(!is.na(dat$hml_id_undo)) + 1, 4, pad = 0))
  }
  
  dat$hml_id[which(dat$part_id == (input$idPick))] <- new_hml_id
  dat$hml_id_created_date[which(dat$part_id == (input$idPick))] <- as.character(format(Sys.Date(), "%Y-%m-%d"))
  
  dat
})

downloadNewData <- observe({
  if(isTruthy(input$saveId)){
    isolate({
      
      new_dat <- dat
      
      if(!is.na(new_dat$hml_id_undo[which(new_dat$part_id == (input$idPick))])){
        new_hml_id <- new_dat$hml_id_undo[which(new_dat$part_id == (input$idPick))]
        new_dat$hml_id_undo[which(new_dat$part_id == (input$idPick))] <- NA
      }else{
        new_hml_id <- paste0("HML", str_pad(sum(!is.na(dat$hml_id)) + sum(!is.na(dat$hml_id_undo)) + 1, 4, pad = 0))
      }
      
      new_dat$hml_id[which(new_dat$part_id == (input$idPick))] <- new_hml_id
      new_dat$hml_id_created_date[which(new_dat$part_id == (input$idPick))] <- as.character(format(Sys.Date(), "%Y-%m-%d"))})
    
    write.csv(new_dat, file = "deidentified_id_data.csv", row.names = F)
    
    dat <<- read.csv("deidentified_id_data.csv")
    # Saves the modified file to Google Drive into the HML Data shared drive
    drive_put("deidentified_id_data.csv", path=drive_find(pattern="HML Data", corpus="allDrives"))
    # Pop up status message and page reload
    shinyalert::shinyalert('Saved', callbackJS = "function() {location.reload()}")
  }
})

# Undo HML ID assignment -------------
# Filter IDs by input area areaPick and display assigned IDs
id_choices_undo <- reactive(
  filter(dat, area == input$areaPick, !is.na(hml_id))
)

downloadNewDataUndo <- observe({
  if(isTruthy(input$saveIdUndo)){
    new_dat <- dat
    
    new_dat$hml_id_undo[which(new_dat$hml_id == input$idPickUndo)] <- input$idPickUndo
    new_dat$hml_id[which(new_dat$hml_id == input$idPickUndo)] <- NA
    
    write.csv(new_dat, file = "deidentified_id_data.csv", row.names = F)
    
    # Saves the modified file to Google Drive into the HML Data shared drive
    drive_put("deidentified_id_data.csv", path=drive_find(pattern="HML Data", corpus="allDrives"))
    # Pop up status message and page reload
    shinyalert::shinyalert('Saved Undo', callbackJS = "function() {location.reload()}")
  }
})

```



<br>

{.sidebar}
===================

<br>

```{r select area}

# Select recruitment area
radioButtons("areaPick", label = "Please select the participant's recruitment area.",
            choices = c("Atlanta", "Baltimore", "Miami", "Tucson"))

```

# Generate New HML ID

## Row

#### 

<center>

```{r display id dropdown}

# Display IDs from selected area (areaPick)
renderUI(
  selectInput("idPick", label = "Select the participant's MindCrowd ID.",
              choices = c("",id_choices()$part_id), selected = NULL)
)

```

```{r display participant info}

# Display selected participant's (idPick) demographics
renderUI(
  HTML(
    if(isTruthy(input$idPick)){
      kable(picked_id_data() %>% select(participant_id:sex),
            col.names = c("Mindcrowd ID", "Truncated Mindcrowd ID", "Area", "Age Group", "Sex"),
            align = "c") %>%
        kable_styling(full_width = FALSE)
    }
  )
)

```

</center>

```{r check if participant has id}

# Gives feedback for whether participant already has an HML ID saved
renderText(
  HTML(
    if(isTruthy(input$idPick)){
      if(!is.na((picked_id_data()$hml_id))){ 
        # If participant already has an HMl ID
        paste0("This participant was assigned HML ID ", picked_id_data()$hml_id," on ", as.Date(picked_id_data()$hml_id_created_date) %>% format("%b %d, %Y"), ".")
      }else{ 
        # If person doesn't have an ID yet
        "This participant does not have an HML ID yet."
      }
    }
  )
)

```

```{r eligibility confirmation}

# Get user input for whether participant is eligible for study (eligiblePick) and doesn't have an HML ID
renderUI(
  # Display if user selects an ID
  if(isTruthy(input$idPick)){ 
    # If participant does not have an HML ID
    if(is.na((picked_id_data()$hml_id))){
      radioButtons("eligiblePick", label = "Is this person eligible for the study?",
                   choices = c("Yes", "No"), selected = "No")
    }
  }
)

```

```{r creating HML ID new}

# Display button if participant is eligible for study
renderUI(
    if(isTruthy(input$idPick) & isTruthy(input$eligiblePick)){
      if(input$eligiblePick == "Yes" & is.na((picked_id_data()$hml_id))){
        actionButton("newId", "Create New HML ID", icon = icon("plus"))
      }
    }
)

# Show data with new HML ID for confirmation
renderUI({
  # If there is an eligiblePick object created
  if(isTruthy(input$idPick) & isTruthy(input$eligiblePick)){ 
    # Only show button if person does not already have an HML ID
    if(input$eligiblePick == "Yes" & is.na((picked_id_data()$hml_id))){
      HTML(
        new_data()[which(dat$part_id == input$idPick),] %>%
          remove_rownames() %>%
          select(-hml_id_undo) %>%
          kable(col.names = c("Mindcrowd ID", "Truncated Mindcrowd ID", "Area", "Age Group", "Sex",
                              "HML ID", "HML Created Date"),
                align = "c") %>%
          kable_styling(full_width = FALSE)
      )
    }
  }
})

```

```{r save new id}

renderUI(
    if(isTruthy(input$idPick) & isTruthy(input$newId)){
      if(is.na((picked_id_data()$hml_id))){
        actionButton("saveId", "Save New HML ID", icon = icon("download"))
      }
    }
)

```

---

# Help

## Row

Undo HML Assignment:

If you assigned a new HML ID by mistake, please select the participants ID from the dropdown menu and press the "Remove" button below.

```{r undo hml dropdown}

# Display IDs from selected area (areaPick) and has an assigned ID
renderUI({
  selectInput("idPickUndo", label = "Select the participant's MindCrowd ID.",
              choices = c("",id_choices_undo()$hml_id), selected = NULL)
})

```


```{r undo hml button}

renderUI(
    if(isTruthy(input$idPickUndo)){
        actionButton("saveIdUndo", "Undo New HML ID", icon = icon("delete-left"))
    }
)

```


<!-- <html> -->

<!-- <p> -->

<!-- Copyright ©: `r format(Sys.time(), "%Y")` StatLab, BIO5 ALL RIGHTS RESERVED -->

<!-- </p> -->

<!-- <p> -->

<!-- Developer: -->

<!-- </p> -->

<!-- <p> -->

<!-- Lisa White, Statistician <br/> -->

<!-- </p> -->
